### ISSUE TITLE
Please add author and descpription to the books

### ISSUE THREAD

**Issue by aenyne** [aenyne/teach-AI-in-business#16]

**Comment by rahullli** [comment]
I would like to work on this issue , can you please add the book's name such that I can add the **author's name** and **desciption of the books .**

**Comment by aenyne** [comment]
hi @rahullli please see in the README.md file under ##Book resources for the books that still are missing an author and description

**Comment by TechLead-21** [comment]
I would like to contribute to this one.

**Comment by rahullli** [comment]
Okay ,  I am working on this issue .

**Comment by aenyne** [comment]
Hi @TechLead-21, thank you - you can add anytime new books and online resources (see other opern issue)

**Comment by Dark-Knight11** [comment]
I would like to contribute to this issue

**Comment by akshithsriram** [comment]
Hi, I would like to contribute to this.
In fact, I have already created a pull request, please verify that once.

**Comment by MarkoKosmajac** [comment]
Hi I would like to contribute to this.

**Comment by sudhatanay** [comment]
Can I contribute?

**Comment by aenyne** [comment]
Thank you all! Sorry, I have already assigned this topic tand will close the issue. If I receive no PR from @rahulli, I will take the first of the ones that you provided

**Comment by ShivaniThevar** [comment]
Hello @aenyne , I had added links to all the books in my commit. Please review it once so that the table gets completed. If you insist I can add them again.

Regards
