### ISSUE TITLE
please check if links are still working

### ISSUE THREAD

**Issue by aenyne** [aenyne/teach-AI-in-business#66]

**Comment by Jay179-sudo** [comment]
Hi! I've checked all the links and I did find some that not working! They are:

Andrew NG Machine Learning Yearning: [https://www.deeplearning.ai/machine-learning-yearning/](url)
Kristian Hammond Practical Artificial Intelligence for Dummies: [http://gunkelweb.com/coms493/texts/AI_Dummies.pdf](url)

Do you want me to edit the Readme.md, remove those items and file an official pull request for it?

**Comment by aenyne** [comment]
yes go on :)
